/*******************************************************************************
* @copyright: Shenzhen Hangshun Chip Technology R&D Co., Ltd 
* @filename:  system_hk32f0xxa.h
* @brief:     CMSIS Cortex-M0 Device Peripheral Access Layer System Source File.
*             This file contains the system clock configuration for HK32F0xxA devices,
*             and is generated by the clock configuration tool 
* @author:    AE Team 
*******************************************************************************/


/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __SYSTEM_HK32F0XXA_H
#define __SYSTEM_HK32F0XXA_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
/** @addtogroup CMSIS
  * @{
  */

/** @addtogroup hk32f0xxa_system
  * @{
  */

/**
  * @brief Define to prevent recursive inclusion
  */


/** @addtogroup HK32F0xxA_System_Includes
  * @{
  */

/**
  * @}
  */

/** @addtogroup HK32F0xxA_System_Exported_types
  * @{
  */

/* Exported types ------------------------------------------------------------*/
/* Exported constants --------------------------------------------------------*/
extern uint32_t SystemCoreClock;          /*!< System Clock Frequency (Core Clock) */

/**
  * @}
  */

/** @addtogroup HK32F0xxA_System_Exported_Constants
  * @{
  */

/**
  * @}
  */

/** @addtogroup HK32F0xxA_System_Exported_Macros
  * @{
  */

/**
  * @}
  */

/** @addtogroup HK32F0xxA_System_Exported_Functions
  * @{
  */

/* Exported macro ------------------------------------------------------------*/
/* Exported functions ------------------------------------------------------- */
extern void SystemInit(void);
extern void SystemCoreClockUpdate(void);
/**
  * @}
  */

#ifdef __cplusplus
}
#endif

#endif /*__SYSTEM_HK32F0XXA_H */

/**
  * @}
  */


